version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: wedding-postgres
    environment:
      POSTGRES_USER: wedding_user
      POSTGRES_PASSWORD: wedding_password
      POSTGRES_DB: wedding_db
    ports:
      - "5432:5432"
    volumes:
      - wedding_postgres_data:/var/lib/postgresql/data

  wedding-backend:
    image: wedding-backend:latest
    container_name: wedding-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wedding_db
      SPRING_DATASOURCE_USERNAME: wedding_user
      SPRING_DATASOURCE_PASSWORD: wedding_password
    ports:
      - "8585:8585"
    depends_on:
      - postgres

volumes:
  wedding_postgres_data: